'use client'
import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { useEditableLocalAuthSession } from '@/editable/components/EditableLocalAuthForms'
export function EditableFooter(){const {session,logout}=useEditableLocalAuthSession();return <footer className="border-t border-[var(--editable-border)] bg-[var(--editable-footer-bg)]"><div className="mx-auto max-w-[var(--editable-container)] px-5 py-14 lg:px-8"><div className="grid gap-10 md:grid-cols-[1.4fr_1fr_1fr]">
  <div><Link href="/" className="text-2xl font-extrabold">Casa<span className="text-violet-400">Silenza</span></Link><p className="mt-4 max-w-md text-sm leading-7 text-[var(--slot4-muted-text)]">Thoughtful guides and trusted local businesses, gathered in one calm place for better everyday decisions.</p></div>
  <div><p className="font-mono text-xs uppercase tracking-[.18em] text-violet-300">Explore</p><div className="mt-4 grid gap-3">{[['Classified','/classified'],['Home','/'],['About','/about'],['Search','/search']].map(([l,h])=><Link key={h} href={h} className="text-sm text-[var(--slot4-muted-text)] hover:text-white">{l}</Link>)}</div></div>
  <div><p className="font-mono text-xs uppercase tracking-[.18em] text-violet-300">Account</p><div className="mt-4 grid gap-3">{session?<><Link href="/create" className="text-sm text-[var(--slot4-muted-text)] hover:text-white">Create <ArrowUpRight className="inline h-3 w-3"/></Link><button onClick={logout} className="text-left text-sm text-[var(--slot4-muted-text)] hover:text-white">Logout</button></>:<><Link href="/login" className="text-sm text-[var(--slot4-muted-text)] hover:text-white">Login</Link><Link href="/signup" className="text-sm text-[var(--slot4-muted-text)] hover:text-white">Sign up</Link></>}</div></div>
  </div><div className="mt-12 flex flex-wrap justify-between gap-3 border-t border-[var(--editable-border)] pt-6 text-xs text-[var(--slot4-soft-muted-text)]"><span>© {new Date().getFullYear()} CasaSilenza</span><span>Quietly useful. Locally connected.</span></div></div></footer>}
