import Link from 'next/link'
import { ArrowRight, Compass, MapPin, Search, Tag } from 'lucide-react'
import type { SitePost } from '@/lib/site-connector'
import type { HomeTimeSection } from '@/lib/task-data'
import type { TaskKey } from '@/lib/site-config'
import { getEditableCategory, getEditableExcerpt, getEditablePostImage, postHref } from '@/editable/cards/PostCards'

type Props={primaryTask:TaskKey;primaryRoute:string;posts:SitePost[];timeSections:HomeTimeSection[]}
const container='mx-auto w-full max-w-[var(--editable-container)] px-5 lg:px-8'
const listings=(props:Props)=>Array.from(new Map([...props.posts,...props.timeSections.flatMap(section=>section.posts)].map(post=>[post.slug||post.id||post.title,post])).values())

function ClassifiedCard({post,href,horizontal=false}:{post:SitePost;href:string;horizontal?:boolean}){
  return <Link href={href} className={`group overflow-hidden rounded-2xl border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] transition duration-500 hover:-translate-y-2 hover:border-violet-400/70 hover:shadow-[0_24px_70px_rgba(91,33,244,.22)] ${horizontal?'grid sm:grid-cols-[190px_1fr]':''}`}>
    <div className={`overflow-hidden bg-[var(--slot4-media-bg)] ${horizontal?'min-h-44':'aspect-[16/10]'}`}><img src={getEditablePostImage(post)} alt={post.title||'Classified listing'} className="h-full w-full object-cover transition duration-700 group-hover:scale-110"/></div>
    <div className="p-5"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-violet-300">{getEditableCategory(post)||'Classified'}</p><h3 className="mt-3 line-clamp-2 text-xl font-bold leading-tight">{post.title||'New classified listing'}</h3><p className="mt-3 line-clamp-2 text-sm leading-6 text-[var(--slot4-muted-text)]">{getEditableExcerpt(post,130)||'Open this listing to view the complete details.'}</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-violet-300">View listing <ArrowRight className="h-4 w-4"/></span></div>
  </Link>
}

export function EditableHomeHero(props:Props){const lead=listings(props)[0];return <section className="relative overflow-hidden border-b border-[var(--editable-border)]"><div className="absolute -right-28 top-10 h-[440px] w-[440px] rounded-full border border-violet-500/40 editable-orbit"><div className="absolute left-10 top-6 h-8 w-8 rounded-full bg-violet-400 blur-sm"/></div><div className={`${container} grid min-h-[620px] items-center gap-12 py-20 lg:grid-cols-[1fr_.9fr]`}><div className="relative z-10"><p className="font-mono text-xs uppercase tracking-[.22em] text-violet-300">Local classifieds · new opportunities</p><h1 className="mt-6 max-w-3xl text-5xl font-extrabold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Find what you need.<br/><span className="bg-gradient-to-r from-violet-300 to-fuchsia-300 bg-clip-text text-transparent">List what you have.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[var(--slot4-muted-text)]">Browse current classified listings for services, opportunities, property, items and local offers in one focused place.</p><form action="/search" className="mt-8 flex max-w-xl overflow-hidden rounded-xl border border-violet-400/40 bg-white p-1.5 shadow-[0_20px_60px_rgba(91,33,244,.3)]"><Search className="ml-3 h-5 w-5 self-center text-violet-600"/><input name="q" placeholder="Search classified listings" className="min-w-0 flex-1 px-3 py-3 text-sm text-slate-950 outline-none"/><button className="rounded-lg bg-[#5b21f4] px-6 font-bold text-white">Search</button></form><div className="mt-6 flex flex-wrap gap-3"><Link href="/classified" className="rounded-full border border-[var(--editable-border)] px-4 py-2 text-sm font-semibold hover:border-violet-400">Browse all classified</Link><Link href="/create" className="rounded-full px-4 py-2 text-sm font-semibold text-violet-300">Post a classified →</Link></div></div>{lead&&<Link href={postHref('classified',lead,'/classified')} className="editable-float relative z-10 hidden overflow-hidden rounded-[2rem] border border-violet-400/40 bg-[var(--slot4-panel-bg)] p-3 shadow-[0_30px_100px_rgba(91,33,244,.3)] lg:block"><img src={getEditablePostImage(lead)} alt={lead.title} className="aspect-[4/3] w-full rounded-[1.5rem] object-cover"/><div className="p-5"><span className="text-xs font-bold text-violet-300">Featured classified</span><h2 className="mt-2 text-2xl font-bold">{lead.title}</h2></div></Link>}</div></section>}

export function EditableStoryRail(props:Props){const posts=listings(props).slice(0,8);if(!posts.length)return null;return <section className="overflow-hidden border-b border-[var(--editable-border)] py-12"><div className={`${container} mb-7 flex items-end justify-between`}><div><p className="font-mono text-xs uppercase tracking-[.2em] text-violet-300">Recently posted</p><h2 className="mt-2 text-3xl font-bold">Latest classified listings</h2></div><Compass className="h-8 w-8 text-violet-400"/></div><div className="editable-marquee flex gap-5 px-5">{[...posts,...posts].map((post,index)=><div key={`${post.id||post.slug}-${index}`} className="w-[310px] shrink-0"><ClassifiedCard post={post} href={postHref('classified',post,'/classified')}/></div>)}</div></section>}

export function EditableMagazineSplit(props:Props){const posts=listings(props).slice(1,7);if(!posts.length)return null;return <section className="bg-[var(--slot4-warm)] py-20"><div className={container}><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div className="lg:sticky lg:top-28 lg:self-start"><Tag className="h-9 w-9 text-violet-400"/><h2 className="mt-5 text-4xl font-extrabold tracking-[-.04em]">Browse current local opportunities.</h2><p className="mt-5 leading-7 text-[var(--slot4-muted-text)]">Explore the newest classified offers, services, notices and available items.</p><Link href="/classified" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-[var(--editable-cta-bg)] px-5 py-3 font-bold">View all classified <ArrowRight className="h-4 w-4"/></Link></div><div className="grid gap-5">{posts.map(post=><ClassifiedCard key={post.id||post.slug} post={post} href={postHref('classified',post,'/classified')} horizontal/>)}</div></div></div></section>}

export function EditableTimeCollections(props:Props){const posts=listings(props).slice(7,15);if(!posts.length)return null;return <section className="py-20"><div className={container}><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-violet-300">More to explore</p><h2 className="mt-2 text-4xl font-extrabold">More classified listings</h2></div><div className="flex items-center gap-2 text-sm text-[var(--slot4-muted-text)]"><MapPin className="h-4 w-4 text-violet-400"/> Browse by location or category</div></div><div className="mt-9 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{posts.map(post=><ClassifiedCard key={post.id||post.slug} post={post} href={postHref('classified',post,'/classified')}/>)}</div></div></section>}

export function EditableHomeCta(){return <section className="border-y border-violet-500/30 bg-[linear-gradient(120deg,#17104d,#5b21f4)]"><div className={`${container} grid gap-8 py-16 md:grid-cols-[1fr_auto] md:items-center`}><div><p className="font-mono text-xs uppercase tracking-[.2em] text-violet-200">Post a classified</p><h2 className="mt-4 text-4xl font-extrabold">Have something to offer?</h2><p className="mt-3 max-w-2xl text-violet-100">Create a classified listing and make it easy for interested visitors to find the details.</p></div><Link href="/create" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-7 py-4 font-extrabold text-violet-900">Create classified <ArrowRight className="h-4 w-4"/></Link></div></section>}
